env:
  commonjs: true
  es6: true
  node: true
parser: '@typescript-eslint/parser'
extends: [google, prettier]
parserOptions:
  ecmaVersion: 2018
rules:
  max-len:
    - error
    - code: 100
  require-jsdoc:
    - off
